"""Type stubs for manim.mobject.mobject."""

from __future__ import annotations

from typing import Any, Callable, Sequence

class Mobject:
    """Base class for all mobjects."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_color(self) -> tuple[float, float, float]: ...
    def set_color(self, color: str | tuple[float, float, float]) -> Mobject: ...
    def add(self, *mobjects: Mobject) -> Mobject: ...
    def remove(self, *mobjects: Mobject) -> Mobject: ...
    def add_updater(self, update_func: Callable[[Mobject], None]) -> Mobject: ...
    def shift(self, vector: tuple[float, float, float] | Sequence[float]) -> Mobject: ...
    def move_to(self, point: tuple[float, float, float] | Sequence[float]) -> Mobject: ...
    def rotate(self, angle: float, **kwargs: Any) -> Mobject: ...
    def scale(self, scale_factor: float) -> Mobject: ...
    def fade(self, darkness: float = ...) -> Mobject: ...
    @property
    def animate(self) -> Any: ...

class VMobject(Mobject):
    """Vector Mobject."""

    pass

class OpenGLMobject(Mobject):
    """OpenGL Mobject."""

    pass

class OpenGLVMobject(VMobject):
    """OpenGL Vector Mobject."""

    pass
